frontend/package-lock.json
frontend/package.json
frontend/src/Components/ModeBtn.jsx
frontend/src/Redux/Store/index.js
frontend/src/Redux/Store/modeSlice.js
frontend/src/index.js

- Redux Toolkit 추가
- 다크모드 redux를 redux toolkit 적용

Feat: Redux Toolkit 추가 및 다크모드 redux 수정

---

backend/aircamp/.gitignore

Chore: .gitignore 에 properties 추가

Chore: .gitignore 에 properties 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/Components/Modal.jsx
frontend/src/Pages/Join.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/Main.jsx
frontend/src/index.js
frontend/src/theme.js

- 회원가입 기초 구현(아이디, 비밀번호, 비밃번호 확인, 이메일, 전화번호, 생년월일)
- 모달 기초 구현 (모달 안은 아직 구현하지 않았음)

Feat: 회원가입 기초 구현

---

frontend/src/App.js
frontend/src/Components/Header.jsx
frontend/src/Components/ModeBtn.jsx

- 헤더의 input 수정
- 헤더의 오른쪽 위의 버튼 수정
- 헤더의 전반적인 색 수정
- 다크모드 버튼 디자인 수정

Design: 헤더 수정

---

frontend/src/App.js
frontend/src/Components/Card.jsx
frontend/src/Components/Header.jsx
frontend/src/Components/ModeBtn.jsx
frontend/src/Pages/Main.jsx

- Main 페이지의 카드 디자인 변경
- 헤더 다크모드일 떄의 색 변경
- 다크모드 버튼이 가장 앞에 나오게 변경(z-index 값 엄청 크게 변경)
- App.js에 다크모드 적용

Design: Main 페이지의 카드 변경

---

frontend/src/Pages/SignUp.jsx

- 이메일 인증 과정 추가 (이메일 인증 후 최종 회원가입 완료)
- 중복 아이디 검사, 중복 회원 검사, 생년월일 유효한지 검사하는 과정 추가 (추후 더 자세히 할 예정)

Feat: 이메일 인증 과정 추가(자세한 과정은 추후 예정)

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/Components/Header.jsx
frontend/src/Pages/AccountSearch.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/SignUp.jsx

- 아이디/비밀번호 찾기 페이지 추가
- 다크모드/라이트모드 전환시 조금 천천히 바뀌게 변경

Feat: 아이디/비밀번호 찾기 페이지 추가

---

frontend/package-lock.json
frontend/src/App.js
frontend/src/Components/Card2.jsx
frontend/src/Components/Header.jsx
frontend/src/Dummy/DummyDatas.js
frontend/src/Pages/Admin.jsx
frontend/src/Pages/Main.jsx
frontend/src/Pages/Mypage.jsx
frontend/src/Pages/Sell.jsx
frontend/src/Style/GlobalStyle.jsx
frontend/src/utils/functions.js

- Admin 페이지 파일 추가
- Card 클릭 시 정보 표시/상세페이지 이동
- Sell 페이지 파일 추가
- 더미데이터 일부 수정

Feat: Card 클릭 시 정보 표시/상세페이지 이동

---

frontend/src/App.js
frontend/src/Components/ProductCRUD.jsx
frontend/src/Components/ProductManage.jsx
frontend/src/Components/SellSideMenu.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/Sell.jsx
frontend/src/Pages/SignUp.jsx

- Sell페이지의 상품등록수정 디자인
- Sell 페이지의 왼쪽 사이드메뉴바
- 몇몇 페이지의 margin-top 수정

Feat: Sell의 상품등록수정 디자인

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/Components/Header.jsx
frontend/src/Components/Reservation.jsx
frontend/src/Components/SellSideMenu.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/Main.jsx
frontend/src/Pages/Sell.jsx
frontend/src/Pages/SignUp.jsx

- test_server라는 폴더, express 이용해 회원가입/로그인/로그아웃 임시 구현
- 터미널에서 test_server로 이동한 후, npm start를 이용해 서버 켜서 이용하면 됩니다
- Sell의 각 페이지들 임시 구현 (추후 다듬을 예정)

Feat: 임시로 로그인/로그아웃/회원가입 구현

---

frontend/src/App.js
frontend/src/Components/Header.jsx

- 테스트 로그인/로그아웃 과정 세션에서 토큰으로 변경

Refactor: 테스트 로그인/로그아웃 과정 토큰으로 변경

---

frontend/src/App.js
frontend/src/Components/Chat.jsx
frontend/src/Components/Chatting/AgentChat.jsx
frontend/src/Components/Chatting/CustomerChat.jsx
frontend/src/Dummy/DummyDatas.js
frontend/src/secret.js

- openAI를 이용해 상담원과의 (하는 것 같은 느낌나는) 채팅 구현

Feat: 상담원과의 채팅

---

frontend/src/App.js
frontend/src/Components/Admin/User.jsx
frontend/src/Components/Admin/UserManagement.jsx
frontend/src/Components/Chat.jsx
frontend/src/Components/Modal/MyModal.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/Main.jsx
frontend/src/Pages/Mypage.jsx
frontend/src/Pages/SignUp.jsx
frontend/src/config.js
frontend/src/utils/MemberFunctions.js
frontend/src/utils/ProductFunctions.js
frontend/src/utils/ReviewFunctions.js
frontend/src/utils/functions.js

- 유저 관련 함수들 추가
- 리뷰 관련 함수들 추가
- 캠프장(상품) 관련 함수들 추가
- 추가된 함수에 맞게 MyModal 조금 수정

Feat: API 명세서에 맞는 함수들 추가

---

backend/aircamp/src/main/java/com/osdoor/aircamp/member/service/MemberService.java

- 관리자가 임시계정을 만들면, 관리자의 계정명이 By필드에 담길수 있도록 하였습니다.
- 일반 회원이 계정을 만들면(회원가입), 해당 사용자의 계정명이 By플드에 담길수 있도록 하였습니다.
- 일반 회원이 회원가입을 하고, 관리자가 해당 계정의 일부 정보를 수정한 경우, 해당 계정의 modifiedBy필드에 관리자의 계정명이 담기도록 하였습니다.

FIX_hw_ By필드 수정

---

backend/aircamp/src/main/java/com/osdoor/aircamp/review/entity/Review.java

- review를 작성하거나 수정한 경우 By필드에 작성자의 계정명이 담길 수 있도록 수정하였습니다.(@PrePersist, @PreUpdate 적용)

FIX_hw_ review를 작성하거나 수정한 경우 By필드에 작성자의 계정명이 담길 수 있도록 수정.

---

frontend/public/index.html
frontend/src/App.js
frontend/src/Components/ChatBox.jsx
frontend/src/Components/Chatting/AIChat.jsx
frontend/src/Components/Header.jsx
frontend/src/Components/Modal/MyModal.jsx
frontend/src/Components/Modal/SeModal.jsx
frontend/src/Pages/Login.jsx
frontend/src/Pages/Main.jsx
frontend/src/Pages/Mypage.jsx
frontend/src/Pages/Test.jsx
frontend/src/config.js
frontend/src/utils/MemberFunctions.js
frontend/src/utils/ProductFunctions.js

- 채팅방 디자인 수정
- 몇몇 모달에 API 명세서 요소 적용

Feat: 채팅방 디자인 수정 및 API 명세서 적용

---

backend/aircamp/src/main/java/com/osdoor/aircamp/reservation/controller/ReservationController.java
backend/aircamp/src/main/java/com/osdoor/aircamp/reservation/dto/ReservationDto.java
backend/aircamp/src/main/java/com/osdoor/aircamp/reservation/service/ReservationService.java

Feat: 사용자의 예약내역 조회 기능 구현

---

frontend/src/App.js
frontend/src/Components/Admin/AdminProductCard.jsx
frontend/src/Components/Admin/AdminProductModal.jsx
frontend/src/Components/Admin/Card.jsx
frontend/src/Components/Admin/Menus.jsx
frontend/src/Components/Admin/ProductManagement.jsx
frontend/src/Components/Admin/User.jsx
frontend/src/Components/Admin/UserManagement.jsx
frontend/src/Components/CheckLogin.jsx
frontend/src/Components/Modal/ProductModal.jsx
frontend/src/Components/Modal/RsModal.jsx
frontend/src/Components/Modal/SeModal.jsx
frontend/src/Components/Review.jsx
frontend/src/Components/Sell/ProductList.jsx
frontend/src/Components/Sell/Registration.jsx
frontend/src/Pages/Admin.jsx
frontend/src/Pages/Detail.jsx
frontend/src/Pages/Mypage.jsx
frontend/src/Pages/NotFound.jsx
frontend/src/Pages/SelectPay.jsx
frontend/src/utils/MemberFunctions.js
frontend/src/utils/ProductFunctions.js
frontend/src/utils/ReviewFunctions.js

Feat: 상품 등록 완료 및 admin에 미디어쿼리 적용

---

backend/aircamp/src/main/java/com/osdoor/aircamp/payment/controller/PaymentController.java
backend/aircamp/src/main/java/com/osdoor/aircamp/payment/service/PaymentService.java

Fix payment hb

---

backend/aircamp/src/main/java/com/osdoor/aircamp/payment/service/PaymentService.java

Fix: 프로퍼티 밸류 수정

---

frontend/src/Components/Admin/User.jsx
frontend/src/Components/Modal/MyModal.jsx
frontend/src/Components/Modal/RsModal.jsx
frontend/src/Components/Modal/SeModal.jsx
frontend/src/Components/Reservation.jsx
frontend/src/Components/Review.jsx
frontend/src/Components/ReviewForm.jsx
frontend/src/Pages/Main.jsx
frontend/src/Pages/Mypage.jsx

- 어드민의 유저에서 이메일 삭제
- 자신의 정보 업데이트 성공 시 모달 닫히게 함
- 예약 확인 모달에서 key값 수정
- 판매자 등록 시 모달 닫히게 함
- 예약 삭제에 마우스 올리면 포인터로 변경됨
- 리뷰 삭제시 새로고침
- 리뷰가 제대로 보이지 않는 점 수정
- 메인 코드 조금 정리
- MyPage에 미디어쿼리 적용

Feat: 디코에 올렸던 거 수정 및 Main 살짝 수정
